spring:
  application:
    name: patient-service
#    docker:
#      compose:
#        enabled: true
#        file: ./compose/docker-compose.yml

    # Needed for testing with H2 database, but not for Docker
#  h2:
#    console:
#      path: /h2-console
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driver-class-name: org.h2.Driver
#    username: admin_viewer
#    password: password
  datasource:
    url: jdbc:postgresql://patient-service-db-cont:5432/patient-service-db
    driver-class-name: org.postgresql.Driver
    username: admin_user
    password: password
  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer

server:
  port: 4000
logging:
  level:
    root: info
    com:
      pm:
        patientservice: debug
billing:
  service:
    address: billing-service
    grpc:
      port: 9001